"""
Defines constants and objects used in CtaStrategy App.
"""

APP_NAME = "SupportResistance"
EVENT_SUPPORT_RESISTANCE_PORTFOLIO = "EVENT_SUPPORT_RESISTANCE_PORTFOLIO"
EVENT_SUPPORT_RESISTANCE_RELOAD = "EVENT_SUPPORT_RESISTANCE_RELOAD"