NAME_DISPLAY_MAP = {
    "editable":"可否手动编辑",
    "vt_symbol": "本地代码",
    "direction": "方向",
    "price": "价格",
    "volume": "数量",
    "time": "执行时间（秒）",
    "interval": "每轮间隔（秒）",
    "db_init": "数据库数据初始化",
    "offset": "开平",
    "active": "算法状态",
    "traded": "成交数量",
    "order_volume": "单笔委托",
    "timer_count": "本轮读秒",
    "total_count": "累计读秒",
    "template_name": "算法模板",
    "display_volume": "挂出数量",
    "stop_price": "触发价格",
    "price_add": "委托超价",
    "capital":"网格资金",
    "guide_price":"基准价格",
    "grid_count":"网格数量",
    "grid_price": "网格交易间距",
    "grid_volume": "网格交易数量",
    "order_type": "委托类型",
    "active_vt_symbol": "主动腿",
    "passive_vt_symbol": "被动腿",
    "spread_up": "价差上限",
    "spread_down": "价差下限",
    "max_pos": "最大持仓",

    "start_time": "开始时间",
    "end_time": "结束时间",

    "min_volume": "最小委托量",
    "max_volume": "最大委托量",
    "volume_change": "委托量变化"
}
